name: kelompok_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  lottie: ^3.1.0
  intl: ^0.19.0
  flutter_bluetooth_printer: ^2.20.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icon/

  fonts:
    - family: MrDafoe
      fonts:
        - asset: assets/fonts/MrDafoe-Regular.ttf
    - family: Pixel
      fonts:
        - asset: assets/fonts/PixelifySans-Regular.ttf
        - asset: assets/fonts/PixelifySans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PixelifySans-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/icon_app.png
